### ISSUE TITLE
ValueError when using "lower_the_better=True" in multiplan

### ISSUE THREAD

**Issue by modantailleur** [mathieulagrange/doce#199]
I get the following error when I try to use "lower_the_better=True" on my metrics:

```
Plan mlp is selected
['step=metric+classifier=PANN']

['step=metric+classifier=PANN']
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/user/MT-SSD/0-PROJETS_INFO/Thèse/exp_27112022/2-ThirdOToMel-27112022/5-main_doce_experiment.py", line 325, in <module>
    doce.cli.main(experiment = experiment, func=step)
  File "/home/user/anaconda3/envs/ModanThesis/lib/python3.9/site-packages/doce/cli.py", line 400, in main
    (data_frame, header, styler, significance, c_metric) = data_frame_display(
  File "/home/user/anaconda3/envs/ModanThesis/lib/python3.9/site-packages/doce/cli.py", line 443, in data_frame_display
    (table, columns, header, nb_factor_columns, modification_time_stamp, significance) = experiment.metric.reduce(
  File "/home/user/anaconda3/envs/ModanThesis/lib/python3.9/site-packages/doce/metric.py", line 468, in reduce
    p_values) = self.reduce_from_npy(
  File "/home/user/anaconda3/envs/ModanThesis/lib/python3.9/site-packages/doce/metric.py", line 140, in reduce_from_npy
    p_values = significance(
  File "/home/user/anaconda3/envs/ModanThesis/lib/python3.9/site-packages/doce/metric.py", line 677, in significance
    p_values[raw_data_row_index, direction_index] = p_value
ValueError: setting an array element with a sequence.
```

And here is an example of one of my metrics:

```
experiment.set_metric(
  name = 'avg_logit_tvb_bce',
  output = 'losses_logit_tvb_bce',
  func = np.mean,
  significance = True,
  percent=False,
  precision=10,
  lower_the_better=True
  )
```

This error doesn't show when I comment the line "lower_the_better=True". Am I doing something wrong ?

**Comment by mathieulagrange** [comment]
this should be fixed with the new version.
