### ISSUE TITLE
`ModuleNotFoundError: No module named 'dataframe_image'`

### ISSUE THREAD

**Issue by lostanlen** [mathieulagrange/doce#210]
After `pip install -e .`

```
>>> import doce
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ext3/doce/doce/__init__.py", line 6, in <module>
    import doce.cli
  File "/ext3/doce/doce/cli.py", line 14, in <module>
    import dataframe_image
ModuleNotFoundError: No module named 'dataframe_image'
```

It seems like it should belong to `install_requires` in `setup.py`

**Comment by mathieulagrange** [comment]
Indeed, thank you for spotting the issue.
